### ISSUE TITLE
About pretrained models

### ISSUE THREAD

**Issue by xuannli** [wkqscut/DCGNet#3]
Hello,  when I use pretrained model, error show missing key(s) in state_dict: "dgcnn.layer0.conv.bias", "dgcnn.layer1.mlps.0.conv.bias", "dgcnn.layer1.mlps.1.conv.bias", "dgcnn.layer1.mlps.2.conv.bias".  I print parameters and find lack bias part of dgcnn.

**Comment by wkqscut** [comment]
Hi, I have fixed some bugs in earlier versions of this release code, please see if it works.
Best regard.
